#!/usr/bin/env python3
import sys
from datetime import datetime

if len(sys.argv) < 2:
    print("usage: tform <timestamp>")
    sys.exit(1)

tms = float(sys.argv[1])
dt = datetime.fromtimestamp(tms / 1000)
print(dt.strftime("%-d. %-m. %Y %H:%M:%S"))
